plugins {
    id 'com.android.application'
}

android {
    namespace 'de.michelcoach'
    compileSdk 34

    defaultConfig {
        applicationId "de.michelcoach"
        minSdk 26
        targetSdk 33
        versionCode 7
        versionName "7.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
}